import { createActionTypes } from '../utils';

const NAMESPACE = 'photo';
const FETCH_PHOTOS_TYPE = 'FETCH_PHOTOS';

const FETCH_PHOTOS_TYPES = createActionTypes(NAMESPACE, FETCH_PHOTOS_TYPE);
const FETCH_PHOTOS_REQUEST = FETCH_PHOTOS_TYPES[0];
const FETCH_PHOTO_SUCCESS = FETCH_PHOTOS_TYPES[1];
const FETCH_PHOTO_FAILURE = FETCH_PHOTOS_TYPES[2];

export default {
  NAMESPACE,
  FETCH_PHOTOS_TYPES,
  FETCH_PHOTOS_REQUEST,
  FETCH_PHOTO_SUCCESS,
  FETCH_PHOTO_FAILURE,
};
